<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<title>Home Page</title>	
</head>
<style type="text/css">
	.header{
		height: 60px;
		background: #f8f9fa ;
	}
	
	.alert {
			padding: 20px;
			background-color: #f44336;
			color: white;
			margin-bottom: 15px;
		}

	@keyframes hideAnimation {
	to {
	    visibility: hidden;
	    width: 0;
	    height: 0;
	  }
	}
	.success{
		background-color: lightgreen ;
		display: block;
		padding: 5px;
		margin: 2px;
		font-weight: bold;
		animation: hideAnimation 0s ease-in 5s;
		animation-fill-mode: forwards;
	}
	.failure{
		background-color: red ;
		display: block;
		padding: 5px;
		margin: 2px;
		font-weight: bold;
		animation: hideAnimation 0s ease-in 1s;
		animation-fill-mode: forwards;
	}
	.notice{
		background-color: orange ;
		display: block;
		padding: 5px;
		margin: 2px;
		font-weight: bold;
		animation: hideAnimation 0s ease-in 0s;
		animation-fill-mode: forwards;
	}
	.link{
		font-family: sans-serif;
		color: black;
		text-decoration: none;
	}
</style>

<body>
<div class="header">
	<div class="links">
		<nav class="navbar navbar-light">
		<a href="index.php?c=product&a=grid" class="navbar navbar-expand-lg navbar-light bg-light link-dark font-monospace">Product</a>
		<a href="index.php?c=category&a=grid" class="navbar navbar-expand-lg navbar-light bg-light link-dark font-monospace">Category</a>
		<a href="index.php?c=customer&a=grid" class="navbar navbar-expand-lg navbar-light bg-light link-dark font-monospace">Customer</a>
		<a href="index.php?c=vendor&a=grid" class="navbar navbar-expand-lg navbar-light bg-light link-dark font-monospace">Vendor</a>
		<a href="index.php?c=salesman&a=grid" class="navbar navbar-expand-lg navbar-light bg-light link-dark font-monospace">Salesman</a>
		<a href="index.php?c=shipping&a=grid" class="navbar navbar-expand-lg navbar-light bg-light link-dark font-monospace">Shipping Method</a>
		<a href="index.php?c=payment&a=grid" class="navbar navbar-expand-lg navbar-light bg-light link-dark font-monospace">Payment Method</a>
		</nav>
	</div>
</div>
<!-- <div class="content">Content</div> -->
<!-- <div class="footer">Footer</div> -->
</body>
</html>