
<!DOCTYPE html>
<html>
	<?php $this->createBlock('Html_Head')->render();?>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>1 Column</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<table border="0" width="100%"> 
	<tr>
		<td height="100"><?php $this->getChild('header')->render();?></td>
	</tr>
	<tr>
		<td ><?php $this->getChild('message')->render();?></td>
	</tr>
	<tr>
		<td height="200"><?php $this->getChild('content')->render();?></td>
	</tr>
	<tr>
		<td height="100"><?php $this->getChild('footer')->render();?></td>
	</tr>
</table>
</body>
</html>