<?php
// print_r($this->getChild('content'));
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Layout</title>
</head>
<body>
<table border="1" width="100%">
	<tr>
		<td colspan="3" height="100">Header</td>
	</tr>
	<tr>
		<td colspan="3" height="20">Message</td>
	</tr>
	<tr>
		<td height="200">Left</td>
		<td height="200"><?php $this->getChild('content')->render();?></td>
		<td height="200">Right</td>
	</tr>
	<tr>
		<td colspan="3" height="100">Footer</td>
	</tr>
</table>
</body>
</html>