<?php
$customers = $this->getData()->getData();
?>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<div class="content">
	<table border="0" width="100%" class="table table-striped">
		<tr>
			<td><h1 align="center">Customer Grid</h1></td>
			<td align="center"><a href="index.php?c=customer&a=add" class="btn btn-primary">Customer ADD</td>
		</tr>
	</table>
	<table border="0" width="100%" class="table table-striped">
		<tr>
			<th>Customer Id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Gender</th>
			<th>Mobile No.</th>
			<th>Status</th>
			<th>created Date</th>
			<th>updated Date</th>
			<th colspan="2">Action</th>
		</tr>
		<?php foreach ($customers as $key => $customer): ?>
		<tr>
			<td align="center"><?php echo $customer->customer_id; ?></td>
			<td><?php echo $customer->first_name; ?></td>
			<td><?php echo $customer->last_name; ?></td>
			<td><?php echo $customer->email; ?></td>
			<td><?php echo $customer->gender; ?></td>
			<td><?php echo $customer->mobile; ?></td>
			<td><?php echo $customer->status; ?></td>
			<td><?php echo $customer->created_at; ?></td>
			<td><?php echo $customer->updated_at; ?></td>
			<td><a href="index.php?c=customer&a=edit&id=<?php echo $customer->customer_id ?>" class="btn btn-dark"> EDIT</a></td>
			<td><a href="index.php?c=customer&a=delete&id=<?php echo $customer->customer_id ?>" class="btn btn-dark"> DELETE</a></td>
		</tr>
		<?php endforeach;?>
	</table>
</div>
