<?php
$paymentMethods = $this->getData();
?>
<div class="content">
	<table width="100%">
		<tr>
			<td colspan="1"><center><h2>Edit Payment Method</h2></center></td>
			<td align="center"><a href="index.php?c=payment&a=grid" class="btn btn-primary">CANCEL</td>
		</tr>
	</table>
	<center>
	<form action="index.php?c=payment&a=save&id=<?php echo $paymentMethods->payment_id;?>" method="post">
	<table width="50%">
		<tr>
			<th colspan="2"><center>Enter Payment Method Information</center></th>
		</tr>
		
		<tr>
			<td class="input-group-text">Name</td>
			<td><input type="text" name="payment[name]" value="<?php echo $paymentMethods->name;?>" class="form-control"></td>
		</tr>
		<?php $statusOptions = [1=>"Active",2=>"Inactive"]; ?>
		<tr>
			<td class="input-group-text">Status</td>
			<td>
				<select name="payment[status]" class="form-select">
					<?php foreach ($statusOptions as $key => $value): ?>
						<option value="<?php echo $key;?>" <?php if($paymentMethods->status==$key) echo "selected";?>><?php echo $value;?></option>
					<?php endforeach ?>
				</select>
			</td>
		</tr>
		<tr>
			<!-- <td>&nbsp;</td> -->
			<td colspan="2"><center><button type="submit" name="submit" class="btn btn-primary">Save</center></td>
		</tr>
	</table>
	</form>
</center>
</div>
