<?php
$attributes = $this->prepareChild()->getData();
?>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<div class="content">
	<table border="0" width="100%" class="table table-striped">
		<tr>
			<td><h1 align="center">Attribute Grid</h1></td>
			<td align="center"><a href="index.php?c=attribute&a=add" class="btn btn-primary">Attribute ADD</td>
		</tr>
	</table>
	<table border="0" width="100%" class="table table-striped">
		<tr>
			<th>Attribute Id</th>
			<th>Entity Type Id</th>
			<th>Code</th>
			<th>Backend Type</th>
			<th>Name</th>
			<th>Status</th>
			<th>Backend Model</th>
			<th>Input Type</th>
			<th colspan="2">Action</th>
		</tr>
		<?php foreach ($attributes as $key => $attribute): ?>
		<tr>
			<td align="center"><?php echo $attribute->attribute_id; ?></td>
			<td><?php echo $attribute->entity_type_id; ?></td>
			<td><?php echo $attribute->code; ?></td>
			<td><?php echo $attribute->backend_type; ?></td>
			<td><?php echo $attribute->name; ?></td>
			<td><?php echo $attribute->status; ?></td>
			<td><?php echo $attribute->status; ?></td>
			<td><?php echo $attribute->input_type; ?></td>
			<td><a href="index.php?c=attribute&a=edit&id=<?php echo $attribute->attribute_id;?>" class="btn btn-primary"> EDIT</a></td>
			<td><a href="index.php?c=attribute&a=delete&id=<?php echo $attribute->attribute_id;?>" class="btn btn-primary"> DELETE</a></td>
		</tr>
		<?php endforeach;?>
	</table>
