<?php
$categories = $this->getData();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Category Grid</title>
	<style type="text/css">
	.content{
		border: 1px solid gray;
		height: 1000px;
	}
	.footer{
		border: 1px solid gray;
		height: 50px;
	}
	</style>
</head>
<body>
<div><?php require_once 'View/Html/home.phtml';?></div>
<div class="content">
	<table border="0" width="100%">
		<tr>
			<td><h1 align="center">Category Grid</h1></td>
			<td align="center"><a href="index.php?c=category&a=add">Category ADD</td>
		</tr>
	</table>
	<table border="1" width="100%">
		<tr>
			<th>Category Id</th>
			<th>Name</th>
			<th>Status</th>
			<th>Description</th>
			<th>Created Date</th>
			<th>Updated Date</th>
			<th colspan="2">Action</th>
		</tr>
		<?php foreach ($categories as $key => $category): ?>
		<tr>
			<td align="center"><?php echo $category->category_id; ?></td>
			<td>
				<?php 
				if($category->parent_category_id==0)
				{
					echo $category->category_name;
				}
				else
				{	
					foreach($categories as $value)
					{
						if($value->category_id == $category->parent_category_id)
						{
							if($value->parent_category_id == 0)
							{
								echo $value->category_name." / ".$category->category_name;
							}
							else
							{
								foreach($categories as $subCategory)
								{
									if($subCategory->category_id == $value->parent_category_id)
									{
										echo $subCategory->category_name." / ".$value->category_name." / ".$category->category_name;
									}
								}
							}
						}
					}
				}
				?>
			
			</td>
			<td><?php echo $category->status; ?></td>
			<td><?php echo $category->description; ?></td>
			<td><?php echo $category->created_at; ?></td>
			<td><?php echo $category->updated_at; ?></td>
			<td><a href="index.php?c=category&a=edit&id=<?php echo $category->category_id ?>"> EDIT</a></td>
			<td><a href="index.php?c=category&a=delete&id=<?php echo $category->category_id ?>"> DELETE</a></td>
		</tr>
		<?php endforeach;?>
	</table>
</div>
<div class="footer"></div>
</body>
</html>