<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Customer ADD</title>
	<style type="text/css">
	.content{
		border: 1px solid gray;
		height: 1000px;
	}
	.footer{
		border: 1px solid gray;
		height: 50px;
	}
	</style>
</head>
<body>
<div><?php require_once 'View/Html/home.phtml';?></div>
<div class="content">
	<table width="100%">
		<tr>
			<td colspan="1"><h2>Add Salesman</h2></td>
			<td align="center"><a href="index.php?c=salesman&a=grid">CANCEL</td>
		</tr>
	</table>
	<form action="index.php?c=salesman&a=insert" method="post">
	<table border="1" width="100%">
		<tr>
			<th align="center" colspan="2">Enter Salesman Information</th>
		</tr>
		<tr>
			<td>First Name</td>
			<td><input type="text" name="salesman[first_name]"></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><input type="text" name="salesman[last_name]"></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" name="salesman[email]"></td>
		</tr>
		<?php $genderOptions = [1=>"Male",2=>"Female",3=>"Other"]; ?>
		<tr>
			<td>Gender</td>
			<td>
				<select name="salesman[gender]">
					<?php foreach ($genderOptions as $key => $value): ?>
						<option value="<?php echo $key;?>"><?php echo $value;?></option>
					<?php endforeach ?>
				</select>
			</td>
		</tr>
		<tr>	
			<td>Mobile No.</td>
			<td><input type="text" name="salesman[mobile]"></td>
		</tr>
		<?php $statusOptions = [1=>"Active",2=>"Inactive"]; ?>
		<tr>
			<td>Status</td>
			<td>
				<select name="salesman[status]">
					<?php foreach ($statusOptions as $key => $value): ?>
						<option value="<?php echo $key;?>"><?php echo $value;?></option>
					<?php endforeach ?>
				</select>
			</td>
		</tr>
		<tr>	
			<td>Company</td>
			<td><input type="text" name="salesman[company]"></td>
		</tr>
		<tr>
			<th align="center" colspan="2">Enter Salesman Address</th>
		</tr>
		<tr>
			<td>Address</td>
			<td><input type="text" name="salesman_address[address]"></td>
		</tr>
		<tr>
			<td>city</td>
			<td><input type="text" name="salesman_address[city]"></td>
		</tr>
		<tr>
			<td>state</td>
			<td><input type="text" name="salesman_address[state]"></td>
		</tr>
		<tr>
			<td>country</td>
			<td><input type="text" name="salesman_address[country]"></td>
		</tr>
		<tr>
			<td>zipcode</td>
			<td><input type="text" name="salesman_address[zipcode]"></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><button type="submit" name="submit">Save</td>
		</tr>
	</table>
	</form>
</div>
<div class="footer"></div>
</body>
</html>