<?php
$salesmen = $this->getData('salesman');
$salesman_address = $this->getData('salesman_address');
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Customer ADD</title>
	<style type="text/css">
	.content{
		border: 1px solid gray;
		height: 1000px;
	}
	.footer{
		border: 1px solid gray;
		height: 50px;
	}
	</style>
</head>
<body>
<div><?php require_once 'View/Html/home.phtml';?></div>
<div class="content">
	<table width="100%">
		<tr>
			<td colspan="1"><h2>Edit Salesman</h2></td>
			<td align="center"><a href="index.php?c=salesman&a=grid">CANCEL</td>
		</tr>
	</table>
	<form action="index.php?c=salesman&a=update" method="post">
	<table border="1" width="100%">
		<tr>
			<th align="center" colspan="2">Edit Salesman Information</th>
		</tr>
		<tr>
			<input type="hidden" name="salesman[salesman_id]" value="<?php echo $salesmen->salesman_id?>">
		</tr>
		<tr>
			<td>First Name</td>
			<td><input type="text" name="salesman[first_name]" value="<?php echo $salesmen->first_name?>"></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><input type="text" name="salesman[last_name]" value="<?php echo $salesmen->last_name?>"></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><input type="text" name="salesman[email]" value="<?php echo $salesmen->email?>"></td>
		</tr>
		<?php $genderOptions = [1=>"Male",2=>"Female",3=>"Other"]; ?>
		<tr>
			<td>Gender</td>
			<td>
				<select name="salesman[gender]">
					<?php foreach ($genderOptions as $key => $value): ?>
						<option value="<?php echo $value;?>"<?php if($salesmen->gender==$key) echo "selected;"?>><?php echo $value;?></option>
					<?php endforeach ?>
				</select>
			</td>
		</tr>
		<tr>	
			<td>Mobile No.</td>
			<td><input type="text" name="salesman[mobile]" value="<?php echo $salesmen->mobile?>"></td>
		</tr>
		<?php $statusOptions = [1=>"Active",2=>"Inactive"]; ?>
		<tr>
			<td>Status</td>
			<td>
				<select name="salesman[status]">
					<?php foreach ($statusOptions as $key => $value): ?>
						<option value="<?php echo $key;?>" <?php if($salesmen->status==$key) echo "selected";?>><?php echo $value;?></option>
					<?php endforeach ?>
				</select>
			</td>
		</tr>
		<tr>	
			<td>Company</td>
			<td><input type="text" name="salesman[company]" value="<?php echo $salesmen->company?>"></td>
		</tr>
		<tr>
			<th align="center" colspan="2">Edit Salesman address</th>
		</tr>
		<tr>
			<input type="hidden" name="salesman_address[address_id]" value="<?php echo $salesman_address->address_id;?>">
		</tr>
		<tr>
			<td>Address</td>
			<td><input type="text" name="salesman_address[address]" value="<?php echo $salesman_address->address;?>"></td>
		</tr>
		<tr>
			<td>City</td>
			<td><input type="text" name="salesman_address[city]" value="<?php echo $salesman_address->city;?>"></td>
		</tr>
		<tr>
			<td>State</td>
			<td><input type="text" name="salesman_address[state]" value="<?php echo $salesman_address->state?>"></td>
		</tr>
		<tr>
			<td>Country</td>
			<td><input type="text" name="salesman_address[country]" value="<?php echo $salesman_address->country?>"></td>
		</tr>
		<tr>
			<td>Zipcode</td>
			<td><input type="text" name="salesman_address[zipcode]" value="<?php echo $salesman_address->zipcode?>"></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><button type="submit" name="submit">Save</td>
		</tr>
	</table>
	</form>
</div>
<div class="footer"></div>
</body>
</html>