<?php
$salesmen = $this->getData();
// $salesmenAddress = $this->getSalesmenAddress();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>salesman grid</title>
	<style type="text/css">
	.content{
		border: 1px solid gray;
		height: 1000px;
	}
	.footer{
		border: 1px solid gray;
		height: 50px;
	}
	</style>
</head>
<body>
<div><?php require_once 'View/Html/home.phtml';?></div>
<div class="content">
	<table border="0" width="100%">
		<tr>
			<td><h1 align="center">Salesman Grid</h1></td>
			<td align="center"><a href="index.php?c=salesman&a=add">Salesman ADD</td>
		</tr>
	</table>
	<table border="1" width="100%">
		<tr>
			<th>Salesman Id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Gender</th>
			<th>Mobile No.</th>
			<th>Status</th>
			<th>Company</th>
			<th>created Date</th>
			<th>updated Date</th>
			<th colspan="2">Action</th>
			<th>Prices</th>
		</tr>
		<?php foreach ($salesmen as $key => $salesman): ?>
		<tr>
			<td align="center"><?php echo $salesman->salesman_id; ?></td>
			<td><?php echo $salesman->first_name; ?></td>
			<td><?php echo $salesman->last_name; ?></td>
			<td><?php echo $salesman->email; ?></td>
			<td><?php echo $salesman->gender; ?></td>
			<td><?php echo $salesman->mobile; ?></td>
			<td><?php echo $salesman->status; ?></td>
			<td><?php echo $salesman->company; ?></td>
			<td><?php echo $salesman->created_at; ?></td>
			<td><?php echo $salesman->updated_at; ?></td>
			<td><a href="index.php?c=salesman&a=edit&id=<?php echo $salesman->salesman_id; ?>"> EDIT</a></td>
			<td><a href="index.php?c=salesman&a=delete&id=<?php echo $salesman->salesman_id; ?>">DELETE</a></td>
			<td><a href="index.php?c=salesman&a=salesmanGrid&id=<?php echo $salesman->salesman_id; ?>">PRICES</a></td>
		</tr>
		<?php endforeach;?>
	</table>
</div>
<div class="footer"></div>
</body>
</html>